/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

//! The portable `Storage` implementations the conformance suite runs against.
//!
//! Each line registers one fixture from `fixtures.rs`. Generic instantiations
//! (e.g. an adapter wrapping another fixture) are written inline, which is why
//! this is a hand-written list rather than a per-struct annotation.
//!
//! The driver generated by `define_driver!` (in `lib.rs`) selects entries for the
//! requested environment and fans the compatible scenarios across them. Portable
//! simulator and integration fixtures live here; additional backend fixtures can
//! live in downstream test targets.

/// Registry of portable `Storage` fixtures. Invoked by the suite entry points with
/// a per-fixture callback (`$cb`) that the driver supplies.
#[macro_export]
macro_rules! storage_fixtures {
    ($cb:path) => {
        $cb!([$crate::fixtures::InMemoryStorageFixture, in_memory, sim]);
        $cb!([
            $crate::fixtures::FaultInjectingStorageFixture<
                $crate::fixtures::InMemoryStorageFixture,
            >,
            fault_injecting_in_memory,
            sim
        ]);
        $cb!([$crate::fixtures::ScopedStorageFixture, scoped, sim]);
        $cb!([
            $crate::fixtures::SqliteFileStorageFixture,
            sqlite_file,
            integration
        ]);
    };
}
