/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

//! Consolidated simulator test invocations for the LogAct commit service.
//!
//! The commit-service suite is generated by `commit_service_sim_suite!`.

use agentbus_tests::fixtures::simtest::FaultInjectingFixture;
use agentbus_tests::fixtures::simtest::SimpleMemoryFixture;
use logact_commit_service_tests::commit_service_sim_suite;
use logact_commit_service_tests::fixtures::ChanneledCommitServiceFixture;
use logact_commit_service_tests::fixtures::CommitServiceV1CountingVoterFixture;
use logact_commit_service_tests::fixtures::CommitServiceV1Fixture;
use logact_commit_service_tests::fixtures::CommitServiceV1LatencyFixture;
use logact_commit_service_tests::fixtures::CommitServiceV1StorageConflictFixture;
use logact_commit_service_tests::fixtures::InMemCommitServiceFixture;
use logact_commit_service_tests::fixtures::RandomRoutingCommitServiceFixture;
use logact_commit_service_v1::StaticConfigPolicyProvider;

commit_service_sim_suite!();

// `run_lin_test_counter_with_denials` asserts an exact commit/abort split that
// only holds for the modulus-2 counting voter, so it can't be a generic scenario
// (which would run against every fixture). Emit it bespoke against just that
// fixture — over the simple in-memory bus and its fault-injecting wrapper —
// reusing the shared per-test codegen.
conformance::sim_test!(
    logact_commit_service_tests::scenarios::run_lin_test_counter_with_denials,
    lin_test_counter_with_denials,
    v1_counting_voter_simple_memory,
    CommitServiceV1CountingVoterFixture<SimpleMemoryFixture>
);
conformance::sim_test!(
    logact_commit_service_tests::scenarios::run_lin_test_counter_with_denials,
    lin_test_counter_with_denials,
    v1_counting_voter_fault,
    CommitServiceV1CountingVoterFixture<FaultInjectingFixture<SimpleMemoryFixture>>
);
